#!/usr/bin/env python

import webbrowser

from application import create_app, db, socketio
from server.switchboard import Switchboard
from server.scheduler import Scheduler
from flask_migrate import upgrade

banner = """
*****************************************************************************

----    ---- ------------ -----------     ------    ----------   ------------ 
****   ****  ************ ***********    ********   ************ ************ 
----  ----   ------------ ----    ---   ----------  --        -- ----         
*********        ****     *********    ****    **** **        ** ************ 
---------        ----     ---------    ------------ --        -- ------------ 
****  ****       ****     ****  ****   ************ **        ** ****         
----   ----      ----     ----   ----  ----    ---- ------------ ------------ 
****    ****     ****     ****    **** ****    **** **********   ************ 

*****************************************************************************


"""

print(banner)

app = create_app()

print("[i] Preparing database")
with app.app_context():
  upgrade()

print("[i] Starting background scheduler")

scheduler = Scheduler()
scheduler.start(app)

print("[i] Starting background thread")

switchboard = Switchboard()
switchboard.start(app)


@app.before_first_request
def initialise_db():
  db.create_all()

if __name__ == "__main__":
  print("[i] KTrade is running. Press ctrl+c to stop...")
  webbrowser.open_new_tab("http://localhost:5000")
  socketio.run(app, debug=False)
