"""Add description to trade status

Revision ID: 4f49d2526718
Revises: e94b0acce9e0
Create Date: 2021-09-18 09:05:22.965339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f49d2526718'
down_revision = 'e94b0acce9e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('what', sa.Text(), nullable=True))

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_status_desc', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_column('order_status_desc')

    with op.batch_alter_table('trade_activities', schema=None) as batch_op:
        batch_op.drop_column('what')

    # ### end Alembic commands ###
