"""initial migration

Revision ID: 534e35784f6b
Revises: 
Create Date: 2021-08-18 17:17:27.343966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534e35784f6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('watched_ticker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watched_ticker')
    op.drop_table('configuration')
    # ### end Alembic commands ###
