"""Setup database

Revision ID: 57483612a5ef
Revises:
Create Date: 2021-09-14 08:18:58.803394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57483612a5ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('total_size', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('amount_ordered', sa.Float(), nullable=True),
    sa.Column('ordered_at', sa.DateTime(), nullable=True),
    sa.Column('order_status', sa.String(), nullable=False),
    sa.Column('filled', sa.Float(), nullable=False),
    sa.Column('remaining', sa.Float(), nullable=True),
    sa.Column('price_at_order', sa.Float(), nullable=True),
    sa.Column('order_type', sa.String(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('stop_order_id', sa.Integer(), nullable=True),
    sa.Column('current_stop', sa.Float(), nullable=True),
    sa.Column('current_position_size', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_order_id'), ['order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_trades_stop_order_id'), ['stop_order_id'], unique=True)

    op.create_table('watched_tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('adr', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('trade_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('when', sa.DateTime(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_activities')
    op.drop_table('watched_tickers')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_stop_order_id'))
        batch_op.drop_index(batch_op.f('ix_trades_order_id'))

    op.drop_table('trades')
    op.drop_table('configurations')
    op.drop_table('accounts')
    # ### end Alembic commands ###
