"""Add order id to activity

Revision ID: e94b0acce9e0
Revises: 57483612a5ef
Create Date: 2021-09-14 17:20:47.231375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e94b0acce9e0'
down_revision = '57483612a5ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_trade_activities_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_activities_order_id'))
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
